name: untitled
version: 1.0.0+1
publish_to: none
description: A new Flutter project.
environment: 
  sdk: '>=3.0.0-290.0.dev <4.0.0'

dependencies: 
  cupertino_icons: ^1.0.5
  firebase_core: ^2.13.0
  cloud_firestore: ^4.7.1
  google_fonts: ^4.0.4
  badges: ^3.1.1
  get_storage: ^2.1.1
  flutter_rounded_date_picker: ^3.0.3
  localization: ^2.1.0
  easy_stepper: ^0.5.2+1
  flutter_staggered_animations: ^1.1.1
  logger: ^1.3.0
  uuid: ^3.0.7
  firebase_auth: ^4.6.1
  shared_preferences: ^2.1.1
  geolocator: ^8.0.1
  geocoding: ^2.0.1
  simple_gradient_text: ^1.2.4
  google_maps_flutter: ^2.2.8
  http: ^1.0.0
  pay: ^1.0.6
  encrypt: ^5.0.1
  share_plus: ^7.0.2
  flutter_form_builder: ^9.0.0
  form_builder_validators: ^9.0.0



  get: ^4.6.5
  date_only_field: ^0.0.13
  flutter:
    sdk: flutter

dependency_overrides:
  intl: ^0.18.1

dev_dependencies: 
  flutter_lints: ^2.0.1
  flutter_test: 
    sdk: flutter

flutter: 
  uses-material-design: true
  assets:
    - assets/
    - assets/images/
