// File generated by FlutterFire CLI.
// ignore_for_file: lines_longer_than_80_chars, avoid_classes_with_only_static_members
import 'package:firebase_core/firebase_core.dart' show FirebaseOptions;
import 'package:flutter/foundation.dart'
    show defaultTargetPlatform, kIsWeb, TargetPlatform;

/// Default [FirebaseOptions] for use with your Firebase apps.
///
/// Example:
/// ```dart
/// import 'firebase_options.dart';
/// // ...
/// await Firebase.initializeApp(
///   options: DefaultFirebaseOptions.currentPlatform,
/// );
/// ```
class DefaultFirebaseOptions {
  static FirebaseOptions get currentPlatform {
    if (kIsWeb) {
      throw UnsupportedError(
        'DefaultFirebaseOptions have not been configured for web - '
        'you can reconfigure this by running the FlutterFire CLI again.',
      );
    }
    switch (defaultTargetPlatform) {
      case TargetPlatform.android:
        return android;
      case TargetPlatform.iOS:
        return ios;
      case TargetPlatform.macOS:
        throw UnsupportedError(
          'DefaultFirebaseOptions have not been configured for macos - '
          'you can reconfigure this by running the FlutterFire CLI again.',
        );
      case TargetPlatform.windows:
        throw UnsupportedError(
          'DefaultFirebaseOptions have not been configured for windows - '
          'you can reconfigure this by running the FlutterFire CLI again.',
        );
      case TargetPlatform.linux:
        throw UnsupportedError(
          'DefaultFirebaseOptions have not been configured for linux - '
          'you can reconfigure this by running the FlutterFire CLI again.',
        );
      default:
        throw UnsupportedError(
          'DefaultFirebaseOptions are not supported for this platform.',
        );
    }
  }

  static const FirebaseOptions android = FirebaseOptions(
    apiKey: 'AIzaSyAVqFpm_e4JBO5XtfnggPxuVtJxqRVjUGE',
    appId: '1:984668260227:android:a8cf297ce3f1daff8458b6',
    messagingSenderId: '984668260227',
    projectId: 'nina-ride',
    storageBucket: 'nina-ride.appspot.com',
  );

  static const FirebaseOptions ios = FirebaseOptions(
    apiKey: 'AIzaSyDZeYxGkd4xeMIG4bqAn2xh_JnhH1nZdbA',
    appId: '1:984668260227:ios:947c3244907596628458b6',
    messagingSenderId: '984668260227',
    projectId: 'nina-ride',
    storageBucket: 'nina-ride.appspot.com',
    androidClientId: '984668260227-r0hd469ke3kb0keiirht5o9ug8dcb6rb.apps.googleusercontent.com',
    iosClientId: '984668260227-shsveueb28nrnt2ta1s9mom3ijopfdn5.apps.googleusercontent.com',
    iosBundleId: 'com.abuzeit.ninaRide',
  );
}
